// print-server.js -- ESC/POS local print server for Windows 7+
var http  = require('http');
var fs    = require('fs');
var path  = require('path');
var os    = require('os');
var exec  = require('child_process').exec;

var PORT         = 3001;
var PRINTER_NAME = process.env.PRINTER_NAME || 'Kassa';
var EXE_PATH     = path.join(os.tmpdir(), 'kc_print.exe');

var ESC = 0x1B;
var GS  = 0x1D;

// Pre-compiled RAW-print helper (embedded as base64)
var EXE_B64 = 'TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAMoZPmoAAAAAAAAAAOAAAgELAQsAAAoAAAAIAAAAAAAAHigAAAAgAAAAQAAAAABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAMQnAABXAAAAAEAAAOAEAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAJAgAAAAgAAAACgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAOAEAAAAQAAAAAYAAAAMAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAEgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAEgAAAACAAUAdCEAAFAGAAABAAAACAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMwBAAQAQAAAQAAEQKOaRgvEHIBAABwKAUAAAoXKAYAAAoCFpoKAheaKAcAAAoLBhICfggAAAooAQAABi0QchMAAHAoBQAAChcoBgAAChIF/hUDAAACEgUfFH0BAAAEEgVyMwAAcH0CAAAEEgVyPwAAcH0EAAAEEQUNCBcSAygDAAAGFy8XCCgCAAAGJnJHAABwKAUAAAoXKAYAAAoIKAUAAAYmCAcHjmkSBCgHAAAGJggoBgAABiYIKAQAAAYmCCgCAAAGJhEEB45pMwtyYQAAcCgFAAAKKhqNAQAAARMGEQYWcmcAAHCiEQYXEQSMCwAAAaIRBhhyfQAAcKIRBhkHjmmMCwAAAaIRBigJAAAKKAUAAAoXKAYAAAoqHgIoCgAACipCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMxOQAAAAAFAGwAAACIAgAAI34AAPQCAAAsAgAAI1N0cmluZ3MAAAAAIAUAAIQAAAAjVVMApAUAABAAAAAjR1VJRAAAALQFAACcAAAAI0Jsb2IAAAAAAAAAAgAAAVcVAhQJAgAAAPolMwAWAAABAAAADgAAAAMAAAAFAAAACQAAAA8AAAALAAAAAgAAAAEAAAABAAAABwAAAAEAAAABAAAAAQAAAAAACgABAAAAAAAGADgAMQAGAD8AMQAGAAgB6QAGAEQBJAEGAGQBJAEGAIsB6QAGAKsBMQAGAL0BMQAGANgBzgEGAOoBMQAGAPYBMQAGAPwBMQAGAAoC6QAGACAC6QAAAAAAAQAAAAAAAQABAAAAEAAXAAAABQABAAEACwERAB8AAAAJAAEACgAGALgANAAGAL8ANwAGAMgANwAGANQANwAGAN4ANAAAAAAAgACRIEkACgABAAAAAACAAJEgVQASAAQAAAAAAIAAkSBiABcABQAAAAAAgACRIHIAEgAIAAAAAACAAJEggAASAAkAAAAAAIAAkSCRABIACgAAAAAAgACRIKAAIAALAFAgAAAAAJEArQAqAA8AbCEAAAAAhhiyADAAEAAAAAEA5QACAAIA5wAAAAMAFQEAAAEA5wAAAAEA5wAAAAIAFwEAAAMAFQEAAAEA5wAAAAEA5wAAAAEA5wAAAAEA5wAAAAIAGQEAAAMAGwECAAQAHQEAAAEAHwEZALIAMAAhALIAOgApALIAMAAxALIAPwA5ALMBRABBAMkBSQBJAN0BTgBRAPEBVABhAAMCVwAJALIAMABpALIAawAuABMAcQAuABsAegBdAJ4BBAEDAEkAAQAAAQUAVQABAAQBBwBiAAEAAAEJAHIAAQAAAQsAgAABAAABDQCRAAEAAAEPAKAAAQAEgAAAAAAAAAAAAAAAAAAAAACCAQAABAAAAAAAAAAAAAAAAQAoAAAAAAADAAIAAAAAPE1vZHVsZT4Aa2NfcHJpbnQuZXhlAEtjUHJpbnQARE9DSU5GT1cAbXNjb3JsaWIAU3lzdGVtAE9iamVjdABWYWx1ZVR5cGUAT3BlblByaW50ZXIAQ2xvc2VQcmludGVyAFN0YXJ0RG9jUHJpbnRlcgBFbmREb2NQcmludGVyAFN0YXJ0UGFnZVByaW50ZXIARW5kUGFnZVByaW50ZXIAV3JpdGVQcmludGVyAE1haW4ALmN0b3IAY2JTaXplAHBEb2NOYW1lAHBPdXRwdXRGaWxlAHBEYXRhdHlwZQBmd1R5cGUAbgBoAFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcwBPdXRBdHRyaWJ1dGUAZABsAGIAYwB3AGFyZ3MAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBDb21waWxhdGlvblJlbGF4YXRpb25zQXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAGtjX3ByaW50AERsbEltcG9ydEF0dHJpYnV0ZQB3aW5zcG9vbC5kcnYAQ29uc29sZQBXcml0ZUxpbmUARW52aXJvbm1lbnQARXhpdABTeXN0ZW0uSU8ARmlsZQBSZWFkQWxsQnl0ZXMASW50UHRyAFplcm8ASW50MzIAU3RyaW5nAENvbmNhdABTdHJ1Y3RMYXlvdXRBdHRyaWJ1dGUATGF5b3V0S2luZAAAABFFAFIAUgA6AGEAcgBnAHMAAB9FAFIAUgA6AE8AcABlAG4AUAByAGkAbgB0AGUAcgAAC08AcgBkAGUAcgAAB1IAQQBXAAAZRQBSAFIAOgBTAHQAYQByAHQARABvAGMAAAVPAEsAABVFAFIAUgA6AHcAcgBvAHQAZQAgAAADLwAAAAAAY7CwKn/GG0mXTVwRtefUewAIt3pcVhk04IkHAAMCDhAYGAQAAQIYCAADCBgIEBEMCQAEAhgdBQgQCAUAAQEdDgMgAAECBggCBg4EIAEBCAQgAQEOBAABAQ4EAAEBCAUAAR0FDgIGGAUAAQ4dHA0HBw4dBRgRDAgRDB0cBSABARE5CAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQAAAOwnAAAAAAAAAAAAAA4oAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAX0NvckV4ZU1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACABAAAAAgAACAGAAAADgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAAFAAAIAAAAAAAAAAAAAAAAAAAAEAAQAAAGgAAIAAAAAAAAAAAAAAAAAAAAEAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAJAAAACgQAAATAIAAAAAAAAAAAAA8EIAAOoBAAAAAAAAAAAAAEwCNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAQAAAABAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsASsAQAAAQBTAHQAcgBpAG4AZwBGAGkAbABlAEkAbgBmAG8AAACIAQAAAQAwADAAMAAwADAANABiADAAAAAsAAIAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAAIAAAADAACAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAAMAAuADAALgAwAC4AMAAAADwADQABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBlAAAAawBjAF8AcAByAGkAbgB0AC4AZQB4AGUAAAAAACgAAgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAACAAAABEAA0AAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAAawBjAF8AcAByAGkAbgB0AC4AZQB4AGUAAAAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADAALgAwAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAAAAAAAADvu788P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCIgc3RhbmRhbG9uZT0ieWVzIj8+DQo8YXNzZW1ibHkgeG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYxIiBtYW5pZmVzdFZlcnNpb249IjEuMCI+DQogIDxhc3NlbWJseUlkZW50aXR5IHZlcnNpb249IjEuMC4wLjAiIG5hbWU9Ik15QXBwbGljYXRpb24uYXBwIi8+DQogIDx0cnVzdEluZm8geG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYyIj4NCiAgICA8c2VjdXJpdHk+DQogICAgICA8cmVxdWVzdGVkUHJpdmlsZWdlcyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjMiPg0KICAgICAgICA8cmVxdWVzdGVkRXhlY3V0aW9uTGV2ZWwgbGV2ZWw9ImFzSW52b2tlciIgdWlBY2Nlc3M9ImZhbHNlIi8+DQogICAgICA8L3JlcXVlc3RlZFByaXZpbGVnZXM+DQogICAgPC9zZWN1cml0eT4NCiAgPC90cnVzdEluZm8+DQo8L2Fzc2VtYmx5Pg0KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAwAAAAgOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';

function ensureExe() {
  if (fs.existsSync(EXE_PATH)) return;
  var buf = Buffer.from(EXE_B64, 'base64');
  fs.writeFileSync(EXE_PATH, buf);
  console.log('   Extracted kc_print.exe -> ' + EXE_PATH);
}

function rawPrint(filePath, printerName, cb) {
  ensureExe();
  var cmd = '"' + EXE_PATH + '" "' + printerName + '" "' + filePath + '"';
  exec(cmd, { timeout: 10000 }, function(err, stdout, stderr) {
    var out = (stdout || '').trim();
    if (out === 'OK') { cb(null); return; }
    cb(new Error(out || (stderr || '').trim() || (err && err.message) || 'unknown'));
  });
}

function toCP866(s) {
  var buf = [];
  for (var i = 0; i < s.length; i++) {
    var c = s.charCodeAt(i);
    if (c < 0x80) { buf.push(c); continue; }
    if (c >= 0x0410 && c <= 0x042F) { buf.push(c - 0x0410 + 0x80); continue; }
    if (c >= 0x0430 && c <= 0x043F) { buf.push(c - 0x0430 + 0xA0); continue; }
    if (c >= 0x0440 && c <= 0x044F) { buf.push(c - 0x0440 + 0xE0); continue; }
    if (c === 0x0401) { buf.push(0xF0); continue; }
    if (c === 0x0451) { buf.push(0xF1); continue; }
    if (c === 0x2116) { buf.push(0xFC); continue; }
    if (c === 0x2014 || c === 0x2013) { buf.push(0x2D); continue; }
    buf.push(0x3F);
  }
  return Buffer.from(buf);
}
function txt(s) { return Buffer.concat([toCP866(s), Buffer.from([0x0A])]); }
function cmd()  { return Buffer.from(Array.prototype.slice.call(arguments)); }

function buildEscPos(o) {
  var items = o.items || [];
  var SEP   = '================================';
  var LINE  = '--------------------------------';
  var now   = new Date().toLocaleString('ru-RU', { timeZone: 'Asia/Almaty' });
  var total = 0;

  var itemRows = items.map(function(it) {
    total += Number(it.qty) || 0;
    var name = String(it.name || '').substring(0, 22);
    while (name.length < 22) name += ' ';
    var qty = String(it.qty || 1);
    while (qty.length < 4) qty = ' ' + qty;
    return txt(name + qty);
  });

  var parts = [
    cmd(ESC, 0x40),
    cmd(ESC, 0x74, 0x11),
    cmd(ESC, 0x61, 0x01),
    cmd(ESC, 0x21, 0x10),
    txt('ZAKAZ #' + (o.order_number || '-')),
    cmd(ESC, 0x21, 0x00),
  ];
  if (o.order_type) parts.push(txt(o.order_type));
  parts.push(txt(SEP));
  parts.push(cmd(ESC, 0x61, 0x00));
  parts.push(txt('Klient: '  + (o.customer || '-')));
  if (o.date) parts.push(txt('Data:   ' + o.date));
  if (o.time) parts.push(txt('Vremja: ' + o.time));
  parts.push(txt(LINE));
  parts.push(cmd(ESC, 0x61, 0x01));
  parts.push(txt('  SOSTAV ZAKAZA  '));
  parts.push(cmd(ESC, 0x61, 0x00));
  parts.push(txt(LINE));
  itemRows.forEach(function(r) { parts.push(r); });
  parts.push(txt(LINE));
  parts.push(txt('Itogo: ' + total));
  if (o.kitchen_notes)    { parts.push(txt(LINE)); parts.push(txt('Kukhne: '   + o.kitchen_notes)); }
  if (o.delivery_address) { parts.push(txt(LINE)); parts.push(txt('Dostavka: ' + o.delivery_address)); }
  parts.push(txt(SEP));
  parts.push(cmd(ESC, 0x61, 0x01));
  parts.push(txt(now));
  parts.push(txt('')); parts.push(txt(''));
  parts.push(cmd(GS, 0x56, 0x42, 0x00));
  return Buffer.concat(parts);
}

var server = http.createServer(function(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }

  if (req.method === 'GET' && req.url === '/ping') {
    res.writeHead(200);
    res.end(JSON.stringify({ ok: true, printer: PRINTER_NAME }));
    return;
  }

  if (req.method === 'POST' && req.url === '/print') {
    var body = '';
    req.on('data', function(d) { body += d; });
    req.on('end', function() {
      try {
        var order   = JSON.parse(body);
        var buf     = buildEscPos(order);
        var tmpFile = path.join(os.tmpdir(), 'kc_receipt.bin');
        fs.writeFileSync(tmpFile, buf);
        rawPrint(tmpFile, PRINTER_NAME, function(err) {
          if (err) {
            console.error('Print error:', err.message);
            res.writeHead(500); res.end(JSON.stringify({ error: err.message }));
          } else {
            console.log('Printed order #' + order.order_number);
            res.writeHead(200); res.end(JSON.stringify({ ok: true }));
          }
        });
      } catch(e) {
        res.writeHead(400); res.end(JSON.stringify({ error: e.message }));
      }
    });
    return;
  }
  res.writeHead(404); res.end();
});

server.listen(PORT, '127.0.0.1', function() {
  console.log('\nPrint server -> http://localhost:' + PORT);
  console.log('   Printer: ' + PRINTER_NAME);
  ensureExe();
  console.log('   Ready! Press Ctrl+C to stop.\n');
});